### ISSUE TITLE
I am trying to self host locationestimatr 1

### ISSUE THREAD

**Issue by ughdoughnut** [locationestimatr/locationestimatr.github.io#7]
I changed the API for both indexs and made a github page, but I cannot seem to press start and play the game :( any insight on what could have went wrong.

**Comment by RuurdBijlsma** [comment]
could you see if there's an error in the console? ctrl+shift+j to open console in Chrome

**Comment by ughdoughnut** [comment]
> could you see if there's an error in the console? ctrl+shift+j to open console in Chrome

https://imgur.com/a/VWgdZnL

**Comment by ughdoughnut** [comment]
> could you see if there's an error in the console? ctrl+shift+j to open console in Chrome

I'm not that technically literate to know what these might mean 

https://imgur.com/a/VWgdZnL
https://imgur.com/a/aaWumoy

**Comment by RuurdBijlsma** [comment]
don't know what's happening there either, and I'm not really maintaining this project anymore :( sorry I can't help

**Comment by anti4r** [comment]
I am having the same problem, along with a Cross-Origin request blocked to the Google maps API.
